name: CD pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
      name: test and build package
      runs-on: ubuntu-22.04
      container: python:3.9-slim
      steps:
        - uses: actions/checkout@v4
          with:
            ref: master

        - name: install dependencies
          run: |
            pip install --upgrade pip
            pip install -r requirements.txt

        - name: cleanup
          run: |
            rm -rf check-reports
            rm -rf build
            rm -rf dist
            rm -rf jlmathlib.egg-info
            mkdir check-reports

        - name: lint
          run: |
            pylint --output-format=text:lint-report.txt mathlib/

        - name: upload lint report
          uses: actions/upload-artifact@v4
          with:
            name: lint-report
            path: lint-report.txt

        - name: test
          run: |
            pytest --cov=mathlib --cov-fail-under=90 --cov-report=html \
              -v --junit-xml=tests-report.xml

        - name: upload test report
          uses: actions/upload-artifact@v4
          with:
            name: tests-report
            path: tests-report.xml

        - name: upload coverage report
          uses: actions/upload-artifact@v4
          with:
            name: coverage-report
            path: htmlcov

        - name: build
          run: |
            python setup.py sdist bdist_wheel

        - name: upload build result
          uses: actions/upload-artifact@v4
          with:
            name: dist
            path: dist
            
