name: Quality checks on Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
      name: test and build package
      runs-on: ubuntu-22.04
      container: python:3.9-slim
      steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: install dependencies
          run: |
            pip install --upgrade pip
            pip install -r requirements.txt

        - name: lint
          run: |
            pylint --output-format=text:lint-report.txt mathlib/

        - name: test
          run: |
            pytest --cov=mathlib --cov-fail-under=90 --cov-report=html \
              -v --junit-xml=tests-report.xml

        - name: test report
          uses: dorny/test-reporter@v1
          if: success() || failure()
          with:
            name: pytests
            path: tests-report.xml
            reporter: jest-junit
            
